# This deployment file is for creating the k8s deployment in Google Kubernetes Engine
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workout-backend-deployment
  labels:
    app: workout-backend
    type: back-end
spec:
  replicas: 3
  selector:
    matchLabels:
      type: back-end
  template:
    metadata:
      name: workout-backend-pod
      labels:
        app: workout-backend
        type: back-end
    spec:
      serviceAccountName: workout-backend-ksa
      containers:
        - name: workout-backend
          image: eduardoriol/workout-backend:latest
          # These environment variables take the DB secrets in GKE cluster
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db_user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db_password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db_name
        # This container is the proxy that allows connection with Cloud SQL DB
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.17
          command:
            - "/cloud_sql_proxy"
            - "-instances=tidy-federation-279320:europe-west6:workouts=tcp:5432"
          securityContext:
            runAsUser: 65532
      # This takes the secret to login to the Dockerhub and pull the private image
      imagePullSecrets:
        - name: dockerhub-credential
